### ISSUE TITLE
advise to rename to "demo"

### ISSUE THREAD

**Issue by maxlapshin** [membraneframework/membrane-element-fake#9]
Hi!

I'm initial author of flussonic, most comprehensive erlang multimedia stack.

We have recently met with negative meaning of "fake" source and right now are removing it to "demo".

Haven't you met problems with "fake"?

**Comment by mat-hek** [comment]
Hi @maxlapshin, haven't heard of Flussonic, but it sounds interesting, is it open source? Concerning the name, we haven't encountered any problems with "fake". Also, [many popular repositories](https://github.com/search?q=fake) have it in their names. Nevertheless, renaming to "demo" would conflict with [Membrane demo](https://github.com/membraneframework/membrane-demo). Can you elaborate on what exactly made you do the renaming?

**Comment by maxlapshin** [comment]
No, sorry, I have closed sources in 2013 as it was not possible to grow team without sponsorship.
I'm really disappointed with the fact that I cannot share our sources, but it is what brings us money to pay bills and develop =)  In any case, if you want, I can give you license key to take a look.

It is a good sign that you do not experience problems with it, because during last two years "fake news" have got new political meanings.  Our fake source generates video with clocks and color-coded timestamp to make automated tests possible that allows to check that transcoder doesn't change timestamps.

You know, it is very easy to get involved into any naming conflicts, like with racoon library.
